# Generated by Django 4.0.3 on 2022-03-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='addemployee1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('em_name', models.CharField(max_length=100)),
                ('em_email', models.CharField(max_length=100)),
                ('em_place', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'employeeform',
            },
        ),
    ]
