# Generated by Django 4.0.3 on 2022-03-18 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_addemployee1'),
    ]

    operations = [
        migrations.CreateModel(
            name='addstudent1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_name', models.CharField(max_length=100)),
                ('st_regno', models.CharField(max_length=100)),
                ('st_place', models.CharField(max_length=100)),
                ('st_dept', models.CharField(max_length=100)),
                ('st_mob', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'studentform',
            },
        ),
    ]
